// תוכן לימוד קריאה לכיתה א' — מילים מנוקדות עם אימוג'י, מקובצות לפי נושא.
// משמש את משחקי הקריאה (ReadingGame). אימוג'י = "תמונה" ללא צורך בקבצים.
// רמת קושי נגזרת אוטומטית באורך המילה (מספר אותיות ללא ניקוד) — ראה ReadingGame.

export interface ReadItem { word: string; emoji: string }
export interface ReadCategory { id: string; name: string; emoji: string; items: ReadItem[] }

export const READING_CATEGORIES: ReadCategory[] = [
  {
    id: 'animals', name: 'חַיּוֹת', emoji: '🐾',
    items: [
      { word: 'כֶּלֶב', emoji: '🐶' },
      { word: 'חָתוּל', emoji: '🐱' },
      { word: 'פִּיל', emoji: '🐘' },
      { word: 'אַרְיֵה', emoji: '🦁' },
      { word: 'דָּג', emoji: '🐟' },
      { word: 'צִפּוֹר', emoji: '🐦' },
      { word: 'סוּס', emoji: '🐴' },
      { word: 'פָּרָה', emoji: '🐄' },
      { word: 'דֹּב', emoji: '🐻' },
      { word: 'קוֹף', emoji: '🐵' },
      { word: 'אַרְנָב', emoji: '🐰' },
      { word: 'צָב', emoji: '🐢' },
      { word: 'נָמֵר', emoji: '🐯' },
      { word: 'זֶבְּרָה', emoji: '🦓' },
      { word: 'חֲזִיר', emoji: '🐷' },
      { word: 'כֶּבֶשׂ', emoji: '🐑' },
      { word: 'עֵז', emoji: '🐐' },
      { word: 'תַּרְנְגוֹל', emoji: '🐔' },
      { word: 'בַּרְוָז', emoji: '🦆' },
      { word: 'נָחָשׁ', emoji: '🐍' },
      { word: 'צְפַרְדֵּעַ', emoji: '🐸' },
      { word: 'דְּבוֹרָה', emoji: '🐝' },
      { word: 'פַּרְפַּר', emoji: '🦋' },
      { word: 'חִלָּזוֹן', emoji: '🐌' },
      { word: 'כְּרִישׁ', emoji: '🦈' },
      { word: 'יַנְשׁוּף', emoji: '🦉' },
      { word: 'עַכְבָּר', emoji: '🐭' },
      { word: 'נְמָלָה', emoji: '🐜' },
      { word: 'עֲטַלֵּף', emoji: '🦇' },
      { word: 'קַרְנַף', emoji: '🦏' },
      { word: 'גָּמָל', emoji: '🐫' },
      { word: 'צְבִי', emoji: '🦌' },
      { word: 'שׁוּעָל', emoji: '🦊' },
      { word: 'אוֹגֵר', emoji: '🐹' },
      { word: 'סְנָאִי', emoji: '🐿️' },
      { word: 'תֻּכִּי', emoji: '🦜' },
      { word: 'טַוָּס', emoji: '🦚' },
      { word: 'דּוֹלְפִין', emoji: '🐬' },
      { word: 'לִוְיָתָן', emoji: '🐳' },
    ],
  },
  {
    id: 'food', name: 'אֹכֶל', emoji: '🍎',
    items: [
      { word: 'תַּפּוּחַ', emoji: '🍎' },
      { word: 'בָּנָנָה', emoji: '🍌' },
      { word: 'לֶחֶם', emoji: '🍞' },
      { word: 'עוּגָה', emoji: '🍰' },
      { word: 'גְּלִידָה', emoji: '🍦' },
      { word: 'גֶּזֶר', emoji: '🥕' },
      { word: 'עֲנָבִים', emoji: '🍇' },
      { word: 'תּוּת', emoji: '🍓' },
      { word: 'בֵּיצָה', emoji: '🥚' },
      { word: 'גְּבִינָה', emoji: '🧀' },
      { word: 'לִימוֹן', emoji: '🍋' },
      { word: 'אֲבַטִּיחַ', emoji: '🍉' },
      { word: 'פִּיצָה', emoji: '🍕' },
      { word: 'הַמְבּוּרְגֶּר', emoji: '🍔' },
      { word: 'עוּגִיָּה', emoji: '🍪' },
      { word: 'סֻכָּרִיָּה', emoji: '🍬' },
      { word: 'שׁוֹקוֹלָד', emoji: '🍫' },
      { word: 'דֻּבְדְּבָן', emoji: '🍒' },
      { word: 'אַגָּס', emoji: '🍐' },
      { word: 'אֲפַרְסֵק', emoji: '🍑' },
      { word: 'תִּירָס', emoji: '🌽' },
      { word: 'עַגְבָנִיָּה', emoji: '🍅' },
      { word: 'מְלָפְפוֹן', emoji: '🥒' },
      { word: 'פִּטְרִיָּה', emoji: '🍄' },
      { word: 'חָלָב', emoji: '🥛' },
      { word: 'דְּבַשׁ', emoji: '🍯' },
      { word: 'שׁוּם', emoji: '🧄' },
      { word: 'בָּצָל', emoji: '🧅' },
      { word: 'בְּרוֹקוֹלִי', emoji: '🥦' },
      { word: 'אֲנָנָס', emoji: '🍍' },
      { word: 'קוֹקוֹס', emoji: '🥥' },
      { word: 'מַנְגּוֹ', emoji: '🥭' },
      { word: 'פּוֹפְּקוֹרְן', emoji: '🍿' },
      { word: 'בָּשָׂר', emoji: '🍖' },
      { word: 'נַקְנִיק', emoji: '🌭' },
    ],
  },
  {
    id: 'objects', name: 'חֲפָצִים', emoji: '🎒',
    items: [
      { word: 'כִּסֵּא', emoji: '🪑' },
      { word: 'סֵפֶר', emoji: '📖' },
      { word: 'כַּדּוּר', emoji: '⚽' },
      { word: 'שָׁעוֹן', emoji: '⏰' },
      { word: 'מַפְתֵּחַ', emoji: '🔑' },
      { word: 'טֵלֵפוֹן', emoji: '📱' },
      { word: 'נַעַל', emoji: '👟' },
      { word: 'כּוֹבַע', emoji: '🧢' },
      { word: 'מַתָּנָה', emoji: '🎁' },
      { word: 'בָּלוֹן', emoji: '🎈' },
      { word: 'עִפָּרוֹן', emoji: '✏️' },
      { word: 'מִטְרִיָּה', emoji: '☂️' },
      { word: 'מִסְפָּרַיִם', emoji: '✂️' },
      { word: 'פַּטִּישׁ', emoji: '🔨' },
      { word: 'סַבּוֹן', emoji: '🧼' },
      { word: 'נוּרָה', emoji: '💡' },
      { word: 'מַצְלֵמָה', emoji: '📷' },
      { word: 'מַחְשֵׁב', emoji: '💻' },
      { word: 'מַזְלֵג', emoji: '🍴' },
      { word: 'כַּף', emoji: '🥄' },
      { word: 'סַכִּין', emoji: '🔪' },
      { word: 'כּוֹס', emoji: '🥤' },
      { word: 'דֶּגֶל', emoji: '🚩' },
      { word: 'מַטְבֵּעַ', emoji: '🪙' },
      { word: 'מִשְׁקָפַיִם', emoji: '👓' },
      { word: 'סֻלָּם', emoji: '🪜' },
      { word: 'דְּלִי', emoji: '🪣' },
      { word: 'מַגְנֵט', emoji: '🧲' },
      { word: 'מִבְרֶשֶׁת', emoji: '🪥' },
      { word: 'נֵר', emoji: '🕯️' },
    ],
  },
  {
    id: 'nature', name: 'טֶבַע', emoji: '🌳',
    items: [
      { word: 'שֶׁמֶשׁ', emoji: '☀️' },
      { word: 'יָרֵחַ', emoji: '🌙' },
      { word: 'כּוֹכָב', emoji: '⭐' },
      { word: 'עֵץ', emoji: '🌳' },
      { word: 'פֶּרַח', emoji: '🌸' },
      { word: 'עָנָן', emoji: '☁️' },
      { word: 'גֶּשֶׁם', emoji: '🌧️' },
      { word: 'אֵשׁ', emoji: '🔥' },
      { word: 'קֶשֶׁת', emoji: '🌈' },
      { word: 'שֶׁלֶג', emoji: '❄️' },
      { word: 'הַר', emoji: '⛰️' },
      { word: 'יָם', emoji: '🌊' },
      { word: 'מַיִם', emoji: '💧' },
      { word: 'חוֹף', emoji: '🏖️' },
      { word: 'מִדְבָּר', emoji: '🏜️' },
      { word: 'בַּרְקָן', emoji: '🌋' },
      { word: 'עָלֶה', emoji: '🍃' },
    ],
  },
  {
    id: 'colors', name: 'צְבָעִים', emoji: '🌈',
    items: [
      { word: 'אָדֹם', emoji: '🔴' },
      { word: 'כָּחֹל', emoji: '🔵' },
      { word: 'יָרֹק', emoji: '🟢' },
      { word: 'צָהֹב', emoji: '🟡' },
      { word: 'סָגֹל', emoji: '🟣' },
      { word: 'כָּתֹם', emoji: '🟠' },
      { word: 'שָׁחֹר', emoji: '⚫' },
      { word: 'לָבָן', emoji: '⚪' },
      { word: 'חוּם', emoji: '🟤' },
      { word: 'וָרֹד', emoji: '🩷' },
    ],
  },
  {
    id: 'body', name: 'גּוּף הָאָדָם', emoji: '🖐️',
    items: [
      { word: 'עַיִן', emoji: '👁️' },
      { word: 'אֹזֶן', emoji: '👂' },
      { word: 'אַף', emoji: '👃' },
      { word: 'פֶּה', emoji: '👄' },
      { word: 'יָד', emoji: '✋' },
      { word: 'רֶגֶל', emoji: '🦵' },
      { word: 'שֵׁן', emoji: '🦷' },
      { word: 'לֵב', emoji: '❤️' },
      { word: 'מֹחַ', emoji: '🧠' },
      { word: 'לָשׁוֹן', emoji: '👅' },
    ],
  },
  {
    id: 'family', name: 'מִשְׁפָּחָה', emoji: '👨‍👩‍👧',
    items: [
      { word: 'תִּינוֹק', emoji: '👶' },
      { word: 'יֶלֶד', emoji: '👦' },
      { word: 'יַלְדָּה', emoji: '👧' },
      { word: 'אַבָּא', emoji: '👨' },
      { word: 'אִמָּא', emoji: '👩' },
      { word: 'סַבָּא', emoji: '👴' },
      { word: 'סַבְתָּא', emoji: '👵' },
    ],
  },
  {
    id: 'vehicles', name: 'כְּלֵי תַּחְבּוּרָה', emoji: '🚗',
    items: [
      { word: 'מְכוֹנִית', emoji: '🚗' },
      { word: 'אוֹטוֹבּוּס', emoji: '🚌' },
      { word: 'רַכֶּבֶת', emoji: '🚂' },
      { word: 'אוֹפַנַּיִם', emoji: '🚲' },
      { word: 'מָטוֹס', emoji: '✈️' },
      { word: 'מַסּוֹק', emoji: '🚁' },
      { word: 'אֳנִיָּה', emoji: '🚢' },
      { word: 'חֲלָלִית', emoji: '🚀' },
      { word: 'מַשָּׂאִית', emoji: '🚚' },
      { word: 'אוֹפַנּוֹעַ', emoji: '🏍️' },
      { word: 'מוֹנִית', emoji: '🚕' },
      { word: 'אַמְבּוּלַנְס', emoji: '🚑' },
      { word: 'כַּבָּאִית', emoji: '🚒' },
      { word: 'טְרַקְטוֹר', emoji: '🚜' },
      { word: 'קַטְנוֹעַ', emoji: '🛵' },
      { word: 'סִירָה', emoji: '⛵' },
    ],
  },
  {
    id: 'clothes', name: 'בְּגָדִים', emoji: '👕',
    items: [
      { word: 'חֻלְצָה', emoji: '👕' },
      { word: 'מִכְנָסַיִם', emoji: '👖' },
      { word: 'שִׂמְלָה', emoji: '👗' },
      { word: 'גֶּרֶב', emoji: '🧦' },
      { word: 'מְעִיל', emoji: '🧥' },
      { word: 'צָעִיף', emoji: '🧣' },
      { word: 'כְּפָפוֹת', emoji: '🧤' },
      { word: 'נַעַל', emoji: '👟' },
      { word: 'כּוֹבַע', emoji: '🧢' },
    ],
  },
  {
    id: 'house', name: 'בַּיִת', emoji: '🏠',
    items: [
      { word: 'בַּיִת', emoji: '🏠' },
      { word: 'דֶּלֶת', emoji: '🚪' },
      { word: 'חַלּוֹן', emoji: '🪟' },
      { word: 'מִטָּה', emoji: '🛏️' },
      { word: 'סַפָּה', emoji: '🛋️' },
      { word: 'אַמְבַּטְיָה', emoji: '🛁' },
      { word: 'מִקְלַחַת', emoji: '🚿' },
    ],
  },
  {
    id: 'sport', name: 'סְפּוֹרְט', emoji: '⚽',
    items: [
      { word: 'כַּדּוּרֶגֶל', emoji: '⚽' },
      { word: 'כַּדּוּרְסַל', emoji: '🏀' },
      { word: 'טֶנִיס', emoji: '🎾' },
      { word: 'שְׂחִיָּה', emoji: '🏊' },
      { word: 'רִיצָה', emoji: '🏃' },
      { word: 'גְּלִישָׁה', emoji: '🏄' },
    ],
  },
  {
    id: 'instruments', name: 'כְּלֵי נְגִינָה', emoji: '🎸',
    items: [
      { word: 'גִּיטָרָה', emoji: '🎸' },
      { word: 'פְּסַנְתֵּר', emoji: '🎹' },
      { word: 'תֹּף', emoji: '🥁' },
      { word: 'חֲצוֹצְרָה', emoji: '🎺' },
      { word: 'כִּנּוֹר', emoji: '🎻' },
      { word: 'מִיקְרוֹפוֹן', emoji: '🎤' },
      { word: 'אָזְנִיּוֹת', emoji: '🎧' },
    ],
  },
]
